# Generated by Django 5.0.4 on 2024-11-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_debitcard_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
