# Generated by Django 5.0.4 on 2024-11-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_debitcard_cvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
