# Generated by Django 5.0.4 on 2024-11-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_sucursal'),
    ]

    operations = [
    ]
