# Generated by Django 5.0.4 on 2024-11-29 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_add_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
    ]
