# Generated by Django 5.0.4 on 2024-11-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_sucursal_direccion_alter_sucursal_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
