# Generated by Django 5.0.4 on 2024-11-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_sucursal_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_change_sucursal',
            field=models.BooleanField(default=True),
        ),
    ]
