# Generated by Django 5.0.4 on 2024-11-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_customuser_can_change_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
