# Generated by Django 5.0.4 on 2024-11-29 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_emisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
