# Generated by Django 5.0.4 on 2024-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_alter_transferencia_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
    ]
