# Generated by Django 5.0.4 on 2024-11-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_customuser_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='No especificado', max_length=255),
        ),
    ]
