# Generated by Django 5.0.4 on 2025-04-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_alter_userprofile_last_name_creditcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
