# Generated by Django 5.2.8 on 2025-11-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_alter_userprofile_dni_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sucursal_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
